# Generated by Django 5.2.1 on 2025-07-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0002_alter_clientprofile_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
    ]
