# Generated by Django 5.2.1 on 2025-06-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('service_provider', 'Service Provider'), ('admin', 'Admin')], max_length=20),
        ),
    ]
