# Generated by Django 5.2.1 on 2025-06-06 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceprovider',
            old_name='fist_name',
            new_name='first_name',
        ),
    ]
