# Generated by Django 5.2.1 on 2025-06-24 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0004_appointment_email_appointment_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='provider',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='serviceapp.serviceprovider'),
        ),
    ]
