# Generated by Django 5.2.1 on 2025-06-24 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0005_alter_service_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='service_name',
        ),
    ]
