# Generated by Django 5.2.1 on 2025-07-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0007_alter_appointment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='profile_image',
            field=models.ImageField(default='provider/profile/default.jpg', upload_to='provider/profile/'),
        ),
    ]
