# Generated by Django 5.2.1 on 2025-07-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0008_serviceprovider_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='profile_image',
            field=models.ImageField(upload_to='provider/profile/'),
        ),
    ]
