# Generated by Django 5.2.1 on 2025-07-10 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0009_alter_serviceprovider_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceprovider',
            old_name='description',
            new_name='bio',
        ),
    ]
