# Generated by Django 5.2.1 on 2025-07-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0010_rename_description_serviceprovider_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='timezone',
            field=models.CharField(default='UTC', help_text='Preferred timezone for this provider', max_length=50),
        ),
    ]
